name : First Test
on : 
    push : 
        branches : 
            - master
jobs : 
    first-job:
        runs-on : ubuntu-latest
        steps : 
            - name : Get the code from the repository
              uses : actions/checkout@v3
            - name : Setup node JS
              uses : actions/setup-node@v3
              with : 
                node-version: 18
            - name : Install dependencies
              run : npm ci
            - name : Run Tests
              run : npm test